local randoms = {}
table.insert(randoms, {
	file = nil,
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "explosion_simple",
	sound = "fbi_open_up.mp3",
	delay = 2600,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 100,
	maxDistance = 250,
	probability = 3,
})
table.insert(randoms, {
	file = "ice",
	sound = "ice_ice_baby.mp3",
	delay = nil,
	volume = 5,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "moveit",
	sound = "move_it.mp3",
	delay = 100,
	volume = 5,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "flashbang",
	sound = "flashbang.mp3",
	delay = 2000,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "spin",
	sound = "spin_me_right_round.mp3",
	delay = 300,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "disco",
	sound = "bad_lil_kiddies.ogg",
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "backflip",
	sound = "do_a_flip.ogg",
	delay = 5200,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "backwards",
	sound = "burp.ogg",
	delay = 200,
	volume = 1,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "blind",
	sound = "legally_blind.ogg",
	delay = 1000,
	volume = 5,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "jinxed",
	sound = "gorillaz.ogg",
	delay = 2600,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "change_camera",
	sound = "underwater_poop.ogg",
	delay = nil,
	volume = 2,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "explosion_cool",
	sound = "big_bang.ogg",
	delay = 8000,
	volume = 5,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "barrelroll_multi",
	sound = "barrelroll_multi.ogg",
	delay = 500,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "techno",
	sound = "techno.mp3",
	delay = 2450,
	volume = 5,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "clutch",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "gravity_moon",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "handbrake",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "horn",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "ignition",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "lights_toggle",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "lookback_short",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "rotatecam_short",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "small_jump",
	sound = "jump.ogg",
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "steer_right",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "warning_signal",
	sound = "ALARM.ogg",
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "barrelroll",
	sound = nil,
	delay = nil,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "sneeze",
	sound = "multi_sneeze.ogg",
	delay = 100,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})
table.insert(randoms, {
	file = "fart",
	sound = "fart.mp3",
	delay = 4600,
	volume = 3,
	block_reset = true,
	ghost = false,
	minDistance = 50,
	maxDistance = 250,
	probability = 5,
})

return randoms